#!/usr/bin/env python3
"""Generate the synthetic Hermes `state.db` golden fixture.

Pure synthetic: the SQL below is the whole fixture. No real transcript, no real
Hermes installation and no data copied from any project. The committed bytes are
the contract; `sqlite.expected.json` pins their BLAKE3 fingerprint.

Regeneration is an audit action only (SQLite page layout can differ across
library versions, so regenerated bytes may not match the pinned fingerprint).

Run from this directory:
    python generate_sqlite_fixture.py
"""

import sqlite3
import sys

DB = "state.db"

SCHEMA = """
CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    source TEXT,
    model TEXT,
    title TEXT,
    started_at REAL
);
CREATE TABLE messages (
    id INTEGER PRIMARY KEY,
    session_id TEXT,
    role TEXT,
    content TEXT,
    tool_calls TEXT,
    tool_call_id TEXT,
    tool_name TEXT,
    reasoning TEXT,
    timestamp REAL
);
"""

# Insertion order is deliberately not emission order: the adapter must sort by
# `timestamp, id` (NULLs first, then id), never by insertion or rowid alone.
ROWS = [
    (
        "INSERT INTO sessions VALUES ('hermes-state-sess-a', 'cli', 'synthetic-model',"
        " 'synthetic state session a', 1700000000.5)"
    ),
    (
        "INSERT INTO sessions VALUES ('hermes-state-sess-b', 'cli', 'synthetic-model',"
        " 'synthetic state session b', NULL)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, timestamp) VALUES"
        " (3, 'hermes-state-sess-a', 'assistant', 'third by id', 1700000003.25)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, timestamp) VALUES"
        " (1, 'hermes-state-sess-a', 'user', '  spaced synthetic text  ', 1700000001.125)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, reasoning, timestamp) VALUES"
        " (2, 'hermes-state-sess-a', 'assistant', NULL, 'synthetic compact reasoning', NULL)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, tool_calls, timestamp) VALUES"
        " (6, 'hermes-state-sess-a', 'assistant', NULL,"
        " '[{\"id\":\"call:synthetic-1\",\"type\":\"function\",\"function\":"
        "{\"name\":\"run_command\",\"arguments\":{\"cmd\":\"echo synthetic\"}}}]',"
        " 1700000005.0)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, tool_call_id, tool_name, timestamp)"
        " VALUES (4, 'hermes-state-sess-a', 'tool', 'synthetic tool result', 'call:synthetic-1',"
        " 'run_command', 1700000004.5)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, tool_name, timestamp) VALUES"
        " (5, 'hermes-state-sess-a', 'tool', NULL, 'never_called', NULL)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, tool_calls, timestamp) VALUES"
        " (7, 'hermes-state-sess-b', 'assistant', 'compact call',"
        " '[{\"name\":\"read_file\",\"arguments\":{\"path\":\"/work/placeholder\"}}]',"
        " 1700000010.0)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, tool_name, timestamp) VALUES"
        " (8, 'hermes-state-sess-b', 'tool', 'compact result', 'read_file', 1700000011.0)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, timestamp) VALUES"
        " (9, 'hermes-state-sess-b', 'system', 'synthetic system prompt', 1700000012.0)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, timestamp) VALUES"
        " (10, 'hermes-state-sess-b', 'developer', 'synthetic developer note', 1700000013.0)"
    ),
    (
        "INSERT INTO messages (id, session_id, role, content, timestamp) VALUES"
        " (11, 'hermes-state-sess-b', 'user', 'unicode synthetic 雪 🚀', 1700000014.75)"
    ),
]


def main() -> None:
    conn = sqlite3.connect(DB)
    conn.executescript(SCHEMA)
    for statement in ROWS:
        conn.execute(statement)
    conn.commit()
    conn.close()
    print(f"wrote {DB}")


if __name__ == "__main__":
    sys.exit(main())
